[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.13.2",
    "discord-py>=2.6.4",
    "httpx>=0.28.1",
    "openai>=2.6.1",
    "python-dotenv>=1.2.1",
]
